sonar.projectKey=SaidIa0703_My-Smart-Budget
sonar.organization=saidia0703


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=My-Smart-Budget
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Exclude files not relevant for analysis
sonar.exclusions=**/*.sql,**/node_modules/**,**/.next/**,**/dist/**,**/build/**