name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Backend
        run: docker build -t abedel/my-smart-budget-backend:latest ./APP/MY_budget/backend
      
      - name: Build Frontend
        run: docker build -t abedel/my-smart-budget-frontend:latest ./APP/MY_budget/frontend
      
      - name: Push Backend
        run: docker push abedel/my-smart-budget-backend:latest
      
      - name: Push Frontend
        run: docker push abedel/my-smart-budget-frontend:latest
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~
            rm -rf my-smart-budget || true
            git clone https://github.com/SaidIa0703/my-smart-budget.git my-smart-budget
            cd my-smart-budget/APP/MY_budget
            sudo /usr/local/bin/docker-compose down -v || true
            sudo /usr/local/bin/docker-compose pull
            sudo /usr/local/bin/docker-compose up -d
            volumes:
            postgres_data:
            mongodb_data:
            networks:
            smart-budget-network:
            driver: bridge
